run:
	@yarn dev

install-dependencies:
	@yarn

docker-compose-up:
	@echo "Up application with docker compose ..."
	# @param --build: build project
	# @param --watch: refresh and rebuild project
	@sudo docker compose up --build --watch

docker-compose-down:
	echo "Down application ..."
	docker compose down